import React, {useCallback, useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';
import {NavIcon} from './icons';
import {TraceView} from './TraceView';
import {PricingSettings,BillingSummary} from './PricingSettings';
import type {components} from './api.generated';

type ApprovalCommand=components['schemas']['Approval'];
type RecordRow={id:string;kind:string;status:string;scope:string;body:Record<string,any>;created_at:string;updated_at:string};
const pages=[['home','工作概览','◈'],['messages','收件箱','▣'],['todos','任务','✓'],['calendar','日程','▦'],['reminders','提醒','◷'],['runs','Agent 运行','⌘'],['approvals','审批中心','◇'],['drafts','邮件草稿','▤'],['skills','Skills','✧'],['parsers','Parsers','⌁'],['memory','记忆','◎'],['trust','渐进式信任','△'],['evaluations','评测','▥'],['audit','审计日志','≡'],['model-calls','模型调用','↗'],['settings','设置','⚙']];
const labels:Record<string,string>={active:'进行中',pending:'待审批',queued:'排队中',running:'运行中',waiting_approval:'等待审批',completed:'已完成',completed_with_attention:'需要关注',failed:'失败',unknown:'待核对',published:'已发布',candidate:'候选',archived:'历史版本',rejected:'已拒绝',approved:'已批准',cancelled:'已取消',suspended:'已暂停',passed:'通过',local:'本地',deleted:'已删除'};
async function api(path:string,body?:unknown){const res=await fetch('/api/'+path,{method:body===undefined?'GET':'POST',credentials:'same-origin',headers:body===undefined?{}:{'Content-Type':'application/json','X-ZhiXing-Local':'1'},body:body===undefined?undefined:JSON.stringify(body)});const raw=await res.text();let data;try{data=JSON.parse(raw)}catch{data={detail:raw}}if(!res.ok)throw new Error(typeof data.detail==='string'?data.detail:JSON.stringify(data.detail));return data}
const pretty=(x:unknown)=>JSON.stringify(x,null,2);
function Status({value}:{value:string}){return <span className={'badge '+value}>{labels[value]||value}</span>}
function App(){
 const [page,setPage]=useState('home'),[rows,setRows]=useState<RecordRow[]>([]),[counts,setCounts]=useState<any[]>([]),[cfg,setCfg]=useState<any>({}),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[input,setInput]=useState(''),[detail,setDetail]=useState<any>(null),[editor,setEditor]=useState<{title:string;value:string;save:(s:string)=>Promise<any>}|null>(null),[offset,setOffset]=useState(0),[stats,setStats]=useState<any>({});
 const refresh=useCallback(async()=>{try{if(page==='home'){const result=await api('stats');setCounts(result.counts);setStats(result);setRows((await api('notifications')).items)}else if(page==='settings'){setCfg(await api('settings'));setRows((await api('pairings')).items)}else setRows((await api(page+'?offset='+offset)).items)}catch(e){setError(String(e))}},[page,offset]);
 useEffect(()=>{let source:EventSource|undefined;let cancelled=false;api('session').then(async()=>{const config=await api('settings');if(cancelled)return;setCfg(config);await refresh();if(cancelled)return;source=new EventSource('/api/stream');source.onmessage=()=>void refresh()}).catch(e=>{if(!cancelled)setError(String(e))});return()=>{cancelled=true;source?.close()}},[refresh]);
 async function act(fn:()=>Promise<any>,message='操作已保存'){setBusy(true);setError('');try{await fn();setNotice(message);await refresh()}catch(e){setError(String(e))}finally{setBusy(false)}}
 function jsonEditor(title:string,value:unknown,save:(obj:any)=>Promise<any>){setEditor({title,value:pretty(value),save:async s=>{const r=await save(JSON.parse(s));setEditor(null);return r}})}
 const count=(kind:string,status?:string)=>counts.filter(c=>c.kind===kind&&(!status||c.status===status)).reduce((a,b)=>a+b.count,0);
 async function send(){await act(async()=>{await api('messages',{message_id:crypto.randomUUID(),source:'web',text:input,conversation_id:'inbox'});setInput('')},'消息已进入工作流')}
 function candidate(){jsonEditor('创建候选 · 先评测，再发布',{name:page==='skills'?'todo-extraction':'meeting-template',content:'',rules:page==='parsers'?{pattern:'会议：(?<title>.+)',plan:{summary:'会议提取',actions:[]}}:null,evidence:[]},b=>api(page+'/candidate',b))}
 return <div className="shell"><aside><div className="brand"><img src="/zhixing-mark.svg" alt="知性标志" width="38" height="38"/><div className="brand-name">知性<small>ZhiXing</small></div></div><div className="workspace">个人工作空间 <small>LOCAL WORKSPACE</small></div><nav>{pages.map(([id,name])=><button key={id} className={page===id?'selected':''} onClick={()=>{setPage(id);setOffset(0);setError('');setNotice('')}}><span><NavIcon name={id}/></span>{name}</button>)}</nav><div className="aside-footer"><i/> 本地优先 · 由你掌控</div></aside>
 <main><header><div><span className="eyebrow">ZHIXING / PERSONAL CHIEF OF STAFF</span><h1>{pages.find(p=>p[0]===page)?.[1]}</h1></div><div className="header-right"><span className="mode">{cfg.mode==='demo'?'离线演示模式':'真实模型模式'}</span><button onClick={()=>void refresh()}>刷新</button></div></header>
 {error&&<div role="alert" className="alert">{error}<button onClick={()=>setError('')}>×</button></div>}{notice&&<div role="status" className="notice">{notice}</div>}
 {page==='settings'&&<PricingSettings api={api}/>}
 {page==='home'&&<BillingSummary value={stats.billing}/>}
 {page==='settings'&&<section className="panel"><h3>Jev 辅助评审</h3><div className="settings-grid"><div><small>运行方式</small><strong>{cfg.jev_mode==='shadow'?'影子评审（不改变执行）':'已关闭'}</strong></div><div><small>独立密钥</small><strong>{cfg.jev_configured?'已配置':'待配置'}</strong></div><div><small>模型 / 每日调用上限</small><strong>{cfg.jev_model||'—'} / {cfg.jev_daily_calls??'—'}</strong></div></div><p>在 .env 设置 ZHIXING_JEV_MODE=shadow 和 ZHIXING_JEV_API_KEY 后重启；仅真实模式调用。启用后会将消息正文和动作计划发送给 TypeSafe 评审，可在运行 Trace 查看结果。</p></section>}
 {page==='home'&&<><section className="hero"><div className="eyebrow">MAKE ROOM FOR WHAT MATTERS</div><h2>把信息变成行动。<br/><em>重要的决定，留给你。</em></h2><p>从消息与邮件中整理任务、识别承诺，跟进每一次执行。</p><div className="hero-tag">{cfg.mode==='demo'?'当前使用规则演示，不会真实发送邮件和消息':'模型与工具执行受到风险策略约束'}</div></section><div className="metrics">{[['已接收消息',count('message')],['Agent 运行',count('run')],['等待你审批',count('approval','pending')],['待办任务',count('todo','active')],['平均运行耗时',stats.average_latency_ms==null?'—':(stats.average_latency_ms/1000).toFixed(1)+'s'],['模型 Token',stats.tokens||0],['费用口径','分币种估算'],['解析器命中率',stats.parser_hit_rate==null?'—':Math.round(stats.parser_hit_rate*100)+'%']].map(([label,value])=><div className="metric" key={label}><span>{label}</span><b>{value}</b></div>)}</div></>}
 {['home','messages'].includes(page)&&<section className="panel composer"><h3>交给知性</h3><textarea aria-label="消息内容" value={input} onChange={e=>setInput(e.target.value)} placeholder="例如：明天下午三点组会，今晚整理实验结果发给导师。"/><div><button onClick={()=>setInput('明天下午三点组会，今晚整理实验结果发给导师。')}>填入演示案例</button><button className="primary" disabled={busy||!input.trim()} onClick={()=>void send()}>开始处理 ↗</button></div></section>}
 {page==='settings'?<><section className="panel"><h3>连接与运行环境</h3><div className="settings-grid">{[['模型',cfg.model_configured?'已配置':'待配置'],['飞书',cfg.feishu_configured?'已配置':'待配置'],['QQ 邮箱',cfg.mail_configured?'已配置':'待配置'],['数据目录',cfg.data_dir],['每日模型调用预算',cfg.daily_call_limit],['绑定飞书用户',cfg.feishu_owner||'未绑定']].map(([k,v])=><div key={k}><small>{k}</small><strong>{v}</strong></div>)}</div><p>在项目根目录 .env 配置模型和渠道凭证，重启服务后生效。密钥不进入页面或数据库。</p><button onClick={()=>void act(()=>api('settings',{evolution_enabled:!cfg.evolution_enabled,feishu_groups:cfg.feishu_groups||[]}))}>{cfg.evolution_enabled?'关闭':'启用'}定时 Skill 候选生成</button><button onClick={()=>jsonEditor('配置允许接入的飞书群',{evolution_enabled:cfg.evolution_enabled,feishu_groups:cfg.feishu_groups||[]},b=>api('settings',b))}>允许接入的群</button><button onClick={()=>void act(()=>api('mail/import',{}),'已执行历史邮件导入')}>导入邮箱历史（每次最多100封）</button><details><summary>配置步骤</summary><ol><li>复制 .env.example 为 .env，设置 ZHIXING_MODE=live。</li><li>填写兼容 API 地址、模型名及密钥。</li><li>飞书创建自建应用，启用机器人、长连接、消息事件与卡片回调；填写 App ID 和 Secret。</li><li>私聊机器人后，在下面确认绑定；群聊需加入允许列表。</li><li>QQ 邮箱开启 IMAP/SMTP，用授权码填写 MAIL_PASSWORD。</li></ol></details></section>{rows.map(r=><section className="panel" key={r.id}><h3>飞书绑定申请</h3><code>{r.body.open_id}</code><Status value={r.status}/>{r.status==='candidate'&&<button onClick={()=>void act(()=>api('review/'+r.id+'/publish',{}))}>绑定为本人</button>}</section>)}</>:
 <section className="panel records"><div className="section-title"><h3>{page==='home'?'最近通知':'记录'}</h3><div>{['skills','parsers'].includes(page)&&<><button onClick={candidate}>＋ 创建候选</button><button onClick={()=>jsonEditor('从运行证据生成候选',{name:'todo-extraction',evidence:[]},b=>api(page+'/curate',b))}>生成改进建议</button><button onClick={()=>jsonEditor('添加确认样本',{name:'todo-extraction',split:'holdout',message:{message_id:crypto.randomUUID(),text:'待办：整理实验'},expected:{summary:'提取',actions:[{tool:'create_todo',args:{title:'整理实验'}}]},safety:false},b=>api('samples',b))}>添加评测样本</button></>}{page==='memory'&&<button onClick={()=>jsonEditor('创建记忆候选',{content:'',scope:'web:inbox'},b=>api('memory',b))}>＋ 记忆候选</button>}{['todos','calendar','reminders'].includes(page)&&<button onClick={()=>jsonEditor('新增'+pages.find(p=>p[0]===page)?.[1],page==='todos'?{title:'',owner:'self'}:page==='calendar'?{title:'',start:'2026-09-22T15:00:00+08:00',end:'2026-09-22T16:00:00+08:00'}:{title:'',due_at:'2026-09-22T09:00:00+08:00'},args=>api('actions',{tool:{todos:'create_todo',calendar:'create_calendar',reminders:'create_reminder'}[page],args}))}>＋ 新建</button>}</div></div>
 {!rows.length?<div className="empty"><span>◎</span><h3>这里还没有记录</h3><p>{page==='approvals'?'需要你决定的动作会出现在这里。':'从一条消息开始，知性会保留每一步的来源与结果。'}</p></div>:rows.map(row=><article className="record" key={row.id}><div className="record-top"><div><h3>{row.body.title||row.body.name||row.body.summary||row.body.event_type||row.body.action?.tool||row.body.content?.slice(0,80)||row.body.text?.slice(0,100)||row.body.key||row.id.slice(0,12)}</h3><small>{new Date(row.created_at).toLocaleString('zh-CN')} · {row.scope}{row.body.version?' · v'+row.body.version:''}</small></div><Status value={row.kind==='notification'&&row.status==='pending'?'queued':row.status}/></div>
 {page==='approvals'&&<><p>{row.body.reason}</p><pre>{pretty(row.body.action?.args)}</pre>{row.status==='pending'&&<div className="actions"><button className="primary" disabled={busy} onClick={()=>void act(()=>api('approvals/'+row.id,{decision:'approve',version:row.body.version} satisfies ApprovalCommand))}>批准</button><button onClick={()=>jsonEditor('修改动作参数（保存后需再次批准）',row.body.action.args,args=>api('approvals/'+row.id,{decision:'edit',version:row.body.version,args}))}>修改</button><button onClick={()=>void act(()=>api('approvals/'+row.id,{decision:'reject',version:row.body.version}))}>拒绝</button></div>}</>}
 {['skills','parsers'].includes(page)&&<><p>{row.body.content}</p><div className="actions">{['candidate','draft'].includes(row.status)&&<><button onClick={()=>void act(()=>api('artifacts/'+row.id+'/evaluate',{}),'评测已完成，请查看评测页')}>运行评测</button>{page==='parsers'&&<button onClick={()=>void act(()=>api('artifacts/'+row.id+'/shadow',{}))}>影子比较</button>}<button onClick={()=>void act(()=>api('artifacts/'+row.id+'/publish',{}))}>发布</button><button onClick={()=>void act(()=>api('artifacts/'+row.id+'/reject',{}))}>拒绝</button></>}{row.status==='archived'&&<button onClick={()=>void act(()=>api('artifacts/'+row.id+'/rollback',{}))}>回滚到此版本</button>}<button onClick={()=>setDetail({current:row.body,baseline:rows.find(r=>r.status==='published'&&r.body.name===row.body.name)?.body})}>查看版本对比</button></div></>}
 {['memory','trust'].includes(page)&&<div className="actions">{row.status==='candidate'&&<><button onClick={()=>void act(()=>api('review/'+row.id+'/publish',{}))}>确认生效</button><button onClick={()=>void act(()=>api('review/'+row.id+'/reject',{}))}>拒绝</button></>}{row.status==='published'&&<button onClick={()=>void act(()=>api('review/'+row.id+'/suspend',{}))}>暂停使用</button>}</div>}
 {page==='runs'&&<div className="actions">{Object.entries(row.body.outcomes||{}).filter(([,o]:any)=>['unknown','failed'].includes(o.status)).map(([id])=><button key={id} onClick={()=>jsonEditor('核对外部执行结果',{action_id:id,executed:true,evidence:''},b=>api('reconcile/'+row.id,b))}>核对执行结果</button>)}<button onClick={()=>void act(async()=>setDetail(await api('runs/'+row.id)),'已加载执行链')}>查看执行链</button><button onClick={()=>void act(()=>api('runs/'+row.id+'/replay',{}),'已创建只模拟工具的回放运行')}>安全回放</button>{row.status==='failed'&&<button onClick={()=>void act(()=>api('runs/'+row.id+'/retry',{}))}>安全恢复</button>}{['queued','running','waiting_approval'].includes(row.status)&&<button onClick={()=>void act(()=>api('runs/'+row.id+'/cancel',{}))}>取消运行</button>}</div>}
 {['todos','calendar','reminders'].includes(page)&&<div className="actions">{page==='todos'&&<><button onClick={()=>void act(()=>api('actions',{tool:'update_todo',args:{id:row.id,status:'completed'}}))}>完成</button><button onClick={()=>void act(()=>api('actions',{tool:'update_todo',args:{id:row.id,status:'cancelled'}}))}>取消任务</button><button onClick={()=>jsonEditor('修改任务',{id:row.id,title:row.body.title,deadline:row.body.deadline},args=>api('actions',{tool:'update_todo',args}))}>修改</button></>}{page==='calendar'&&<><button onClick={()=>jsonEditor('修改日程',{id:row.id,title:row.body.title,start:row.body.start,end:row.body.end},args=>api('actions',{tool:'update_calendar',args}))}>修改日程</button><button onClick={()=>jsonEditor('邀请参会人',{id:row.id,recipient:''},args=>api('actions',{tool:'invite_calendar',args}))}>邀请参会人</button></>}{['conflict','unknown'].includes(row.body.sync_status)&&<button onClick={()=>void act(()=>api('sync-resolution/'+row.id,{use_local:true}))}>以本地内容重新申请同步</button>}{page!=='reminders'&&<button onClick={()=>void act(()=>api('actions',{tool:page==='todos'?'sync_todo':'sync_calendar',args:{id:row.id}}))}>同步到飞书</button>}<button onClick={()=>void act(()=>api('actions',{tool:'delete_item',args:{id:row.id}}))}>删除</button><small>同步：{row.body.sync_status||'local'}</small></div>}
 {page==='drafts'&&<button onClick={()=>jsonEditor('发送草稿 · 需要审批',{recipient:row.body.recipient||'',subject:row.body.subject,content:row.body.content},args=>api('actions',{tool:'send_email',args}))}>准备发送</button>}
 <details><summary>查看数据与来源</summary><pre>{pretty(row.body)}</pre><small>ID：{row.id}</small></details></article>)}
 {page!=='home'&&<div className="pagination"><button disabled={!offset} onClick={()=>setOffset(Math.max(0,offset-50))}>上一页</button><span>{offset/50+1}</span><button disabled={rows.length<50} onClick={()=>setOffset(offset+50)}>下一页</button></div>}</section>}
 <footer>知性 · 所有动作可追踪，所有高风险操作由你决定。</footer></main>
 {detail&&<div className="overlay" onClick={()=>setDetail(null)}><section className="modal" onClick={e=>e.stopPropagation()}><div className="section-title"><h2>{detail.trace?'运行 Trace':'版本详情'}</h2><button onClick={()=>setDetail(null)}>关闭</button></div>{detail.trace?<TraceView detail={detail}/>:<pre>{pretty(detail)}</pre>}</section></div>}
 {editor&&<div className="overlay"><section className="modal"><h2>{editor.title}</h2><p>填写真实参数。日期使用带时区的 ISO 格式；证据字段填写记录 ID。</p><ParameterEditor value={editor.value} title={editor.title} onChange={value=>setEditor({...editor,value})}/><div className="actions"><button className="primary" disabled={busy} onClick={()=>void act(()=>editor.save(editor.value))}>保存</button><button onClick={()=>setEditor(null)}>取消</button></div></section></div>}
 </div>
}
const fieldLabels:Record<string,string>={title:'标题',owner:'负责人',deadline:'截止时间（带时区）',start:'开始时间（带时区）',end:'结束时间（带时区）',due_at:'提醒时间（带时区）',recipient:'收件人邮箱 / 飞书 open_id',subject:'主题',content:'内容',scope:'适用会话',evidence:'核对依据',executed:'已确认在外部执行成功'};
function ParameterEditor({value,title,onChange}:{value:string;title:string;onChange:(s:string)=>void}){
 let data:Record<string,any>;try{data=JSON.parse(value)}catch{return <textarea className="json-editor" aria-label="参数编辑器" value={value} onChange={e=>onChange(e.target.value)}/>}
 const advanced=Object.values(data).some(v=>v!==null&&typeof v==='object');
 return advanced?<textarea className="json-editor" aria-label="参数编辑器" value={value} onChange={e=>onChange(e.target.value)}/>:<div className="field-form">{Object.entries(data).filter(([k])=>!['id','action_id'].includes(k)).map(([k,v])=><label key={k}>{fieldLabels[k]||k}{typeof v==='boolean'?<select value={String(v)} onChange={e=>onChange(pretty({...data,[k]:e.target.value==='true'}))}><option value="true">是，已确认成功</option><option value="false">否，已确认没有执行</option></select>:<textarea aria-label={fieldLabels[k]||k} rows={['content','evidence'].includes(k)?4:1} value={v??''} onChange={e=>onChange(pretty({...data,[k]:e.target.value||null}))}/>}</label>)}<details><summary>高级：编辑完整参数</summary><textarea className="json-editor" aria-label="参数编辑器" value={value} onChange={e=>onChange(e.target.value)}/></details></div>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
