import {test,expect} from '@playwright/test';

test('日程审批、执行 Trace、通知与移动端导航',async({page},info)=>{
  test.setTimeout(90000);
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/');
  await expect(page.getByText('离线演示模式',{exact:true})).toBeVisible();
  const response=await page.request.post('/api/mail/demo',{headers:{'X-ZhiXing-Local':'1'},data:{}});
  expect(response.ok()).toBeTruthy();const demo=await response.json();
  await page.reload();
  await page.getByLabel('当前邮箱').selectOption(demo.account_id);
  await page.locator('nav').getByRole('button',{name:'日程',exact:true}).click();
  await page.getByLabel('日程标题',{exact:true}).fill('合成场景：实验复盘');
  await page.getByLabel('开始时间',{exact:true}).fill('2026-10-01T14:00');
  await page.getByLabel('结束时间',{exact:true}).fill('2026-10-01T15:00');
  await page.getByRole('button',{name:'提交日程审批'}).click();
  await expect(page.getByRole('status')).toContainText('已提交审批');
  await page.locator('nav').getByRole('button',{name:'审批中心',exact:true}).click();
  await expect(page.getByRole('button',{name:'批准执行',exact:true})).toBeVisible({timeout:15000});
  await page.getByRole('button',{name:'批准执行',exact:true}).click();
  await page.getByRole('button',{name:'查看执行 Trace',exact:true}).click();
  await expect(page.getByRole('heading',{name:'运行 Trace',exact:true})).toBeVisible();
  await expect(page.locator('.mail-trace')).toContainText('已完成',{timeout:15000});
  await expect(page.locator('.trace-timeline')).toContainText('工具执行结果');
  await page.screenshot({path:info.outputPath('calendar-execution-trace.png'),fullPage:true});
  await page.getByRole('button',{name:'关闭',exact:true}).click();
  await page.locator('nav').getByRole('button',{name:'日程',exact:true}).click();
  await expect(page.getByRole('heading',{name:'合成场景：实验复盘',exact:true})).toBeVisible();
  await page.locator('nav').getByRole('button',{name:/通知与提醒/}).click();
  await expect(page.getByRole('heading',{name:'执行结果',exact:true})).toBeVisible({timeout:15000});
  await page.getByRole('button',{name:'标记已读',exact:true}).first().click();
  await expect(page.locator('.mail-account').filter({hasText:'已读'}).first()).toBeVisible();
  await page.locator('nav').getByRole('button',{name:'运行记录',exact:true}).click();
  await expect(page.getByRole('button',{name:'查看执行 Trace',exact:true})).toBeVisible();
  await page.screenshot({path:info.outputPath('workspace-desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await expect(page.locator('nav').getByRole('button',{name:'邮箱账号',exact:true})).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
  await page.screenshot({path:info.outputPath('workspace-mobile.png'),fullPage:true});
  expect(errors).toEqual([]);
});
