import { test, expect } from '@playwright/test';

test('本地日程创建、编辑、回收与移动端导航', async ({ page }, info) => {
  test.setTimeout(60000);
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await expect(page.getByText('离线演示模式', { exact: true })).toBeVisible();
  const response = await page.request.post('/api/mail/demo', { headers: { 'X-ZhiXing-Local': '1' }, data: {} });
  expect(response.ok()).toBeTruthy();
  const demo = await response.json();
  await page.reload();
  await page.getByLabel('当前邮箱').selectOption(demo.account_id);
  await page.locator('nav').getByRole('button', { name: '日程', exact: true }).click();
  const title = `合成场景：实验复盘 ${Date.now()}`;
  await page.getByLabel('日程标题', { exact: true }).fill(title);
  await page.getByLabel('开始时间', { exact: true }).fill('2026-10-01T14:00');
  await page.getByLabel('结束时间', { exact: true }).fill('2026-10-01T15:00');
  await page.getByRole('button', { name: '保存日程' }).click();
  await expect(page.getByRole('status')).toContainText('本地日程已保存');
  const card = page.locator('section.panel').filter({ has: page.getByRole('heading', { name: title }) });
  await expect(card).toBeVisible({ timeout: 10000 });
  await card.getByRole('button', { name: '编辑日程' }).click();
  await page.getByLabel('日程标题', { exact: true }).fill(title + '（调整）');
  await page.getByRole('button', { name: '保存日程' }).click();
  const updated = page.locator('section.panel').filter({ has: page.getByRole('heading', { name: title + '（调整）' }) });
  await expect(updated).toBeVisible({ timeout: 10000 });
  await updated.getByRole('button', { name: '移入回收站' }).click();
  await expect(updated).toHaveCount(0);
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.locator('nav').getByRole('button', { name: '邮箱账号', exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
  expect(errors).toEqual([]);
});
